services:
  postgres:
    ports:
      - "5432:5432"

  redis:
    ports:
      - "6379:6379"

  backend:
    ports:
      - "9000:9000"
      - "5173:5173"
    volumes:
      - ./backend:/server
      - backend_node_modules:/server/node_modules

  storefront:
    ports:
      - "8000:8000"
    volumes:
      - ./storefront:/app/storefront
      - storefront_node_modules:/app/storefront/node_modules

volumes:
  backend_node_modules:
  storefront_node_modules:
